# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'P08_PromedioNumeros-Load_V2.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(762, 543)
        MainWindow.setStyleSheet("background-color: rgb(174, 220, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_Cargar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Cargar.setGeometry(QtCore.QRect(50, 30, 241, 61))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.btn_Cargar.setFont(font)
        self.btn_Cargar.setStyleSheet("background-color: rgb(130, 0, 2);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:25px;\n"
"border: 3px solid blue;")
        self.btn_Cargar.setObjectName("btn_Cargar")
        self.txt_Calificacion = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_Calificacion.setGeometry(QtCore.QRect(20, 160, 251, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.txt_Calificacion.setFont(font)
        self.txt_Calificacion.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:20px;\n"
"")
        self.txt_Calificacion.setText("")
        self.txt_Calificacion.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_Calificacion.setObjectName("txt_Calificacion")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 120, 151, 21))
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 230, 151, 21))
        self.label_4.setObjectName("label_4")
        self.txt_Resultado = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_Resultado.setGeometry(QtCore.QRect(30, 270, 251, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.txt_Resultado.setFont(font)
        self.txt_Resultado.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:20px;\n"
"")
        self.txt_Resultado.setText("")
        self.txt_Resultado.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_Resultado.setObjectName("txt_Resultado")
        self.btn_Guardar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Guardar.setGeometry(QtCore.QRect(190, 360, 251, 71))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.btn_Guardar.setFont(font)
        self.btn_Guardar.setStyleSheet("background-color: rgb(130, 0, 2);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:25px;\n"
"border: 3px solid blue;")
        self.btn_Guardar.setObjectName("btn_Guardar")
        self.btn_Agregar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Agregar.setGeometry(QtCore.QRect(340, 150, 241, 61))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.btn_Agregar.setFont(font)
        self.btn_Agregar.setStyleSheet("background-color: rgb(130, 0, 2);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:25px;\n"
"border: 3px solid blue;")
        self.btn_Agregar.setObjectName("btn_Agregar")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(360, 0, 151, 21))
        self.label_2.setObjectName("label_2")
        self.txt_lista_calificaciones = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_lista_calificaciones.setGeometry(QtCore.QRect(350, 40, 241, 87))
        self.txt_lista_calificaciones.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:20px;\n"
"")
        self.txt_lista_calificaciones.setObjectName("txt_lista_calificaciones")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 762, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_Cargar.setText(_translate("MainWindow", "Cargar"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; font-style:italic;\">Calificacion:</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; font-style:italic;\">Promedio:</span></p></body></html>"))
        self.btn_Guardar.setText(_translate("MainWindow", "Guardar"))
        self.btn_Agregar.setText(_translate("MainWindow", "Agregar"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; font-style:italic;\">Calificaciones:</span></p></body></html>"))
